export const movieList = [
  {
    id: 1011,
    name: "Black Adam",
    year: "2022",
    runtime: 124,
    rating: 8.2,
    poster: "/images/movies/inception.jpg",
    category: ["fantasy", "action", "adventure"],
    releaseDate: "2022-10-21",
    director: "Jaume Serra",
    writer: ["Adam Sztykiel", "Rory Haines", "Sohrab Noshirvani"],
    actors: [
      "Dwayne Johnson",
      "Aldis Hodge",
      "Pierce Brosnan",
      "Noah Centineo",
      "Sarah Shahi",
      "Quintessa Swindell",
      "Marwan Kenzari",
    ],
    storyline:
      "Nearly 5000 years after he was bestowed with the almighty powers of the Egyptian gods-and imprisoned just as quickly-Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
  },
  {
    id: 1012,
    name: "Joker",
    year: "2019",
    runtime: 137,
    rating: 7.8,
    poster: "/images/movies/joker.jpg",
    category: ["fantasy", "action", "adventure", "drama"],
    releaseDate: "2019-08-03",
    director: "Johnbas T",
    writer: ["Adam Sztykiel", "Rory Haines", "Sohrab Noshirvani"],
    actors: ["Jaoquin Phenix", "Adam Sandler", "Homo Sono", "Bala Centineo"],
    storyline:
      "The Joker's journey portrayal by Jaoquin Phenix tries to find himself in the society of chaos and hunger, but he inadvertently infects himself with a form of mental instability and embracing it.",
  },
  {
    id: 1013,
    name: "Morbius",
    year: "2022",
    runtime: 104,
    rating: 7.0,
    poster: "/images/movies/star-wars.jpg",
    category: ["horror", "action", "adventure"],
    releaseDate: "2022-04-01",
    director: "Daniel Espinosa",
    writer: ["Matt Sazama", "Burk Sharpless"],
    actors: [
      "Jared Leto",
      "Matt Smith",
      "Adria Arjona",
      "Jared Harris",
      "Tyrese Gibson",
      "Al Madrigal",
    ],
    storyline:
      "Biochemist Michael Morbius tries to cure himself of a rare blood disease, but he inadvertently infects himself with a form of vampirism instead.",
  },
  {
    id: 1014,
    name: "Thor: Love and Thunder",
    year: "2022",
    runtime: 118,
    rating: 9.1,
    poster: "/images/movies/lord-of-the-rings.jpg",
    category: ["comedy", "action", "adventure"],
    releaseDate: "2022-07-08",
    director: "Taika Waititi",
    writer: ["Taika Waititi", "Jennifer Kaytin Robinson"],
    actors: [
      "Chris Hemsworth",
      "Christian Bale",
      "Natalie Portman",
      "Tessa Thompson",
      "Russell Crowe",
      "Chris Pratt",
      "Jaimie Alexander",
    ],
    storyline:
      "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
  },
];
